### PR TITLE
Move docs, update fsdocs-tool, add custom theming. Fix other things.

### PR DESCRIPTION
**Pull request by nojaf**
Good stuff

### CODE REVIEW

**Comment by RonaldSchlenker** [comment]
Hey Florian! Thanks for taking the time making the PR. Good stuff indeed :) Here are 2 points:

* the `src/docs` folder contained the editable content of the documentation. This seems to be gone now. I already removed the build output of the docs from the repository some time before. 
* Putting the `FsHttp.sln`, `Directory.Build.props` and also `global.json` in the repo's root isn't what I usually do. I like to have all artifacts that contribute directly to a build output in the `src` folder. There might also be other folders under root with different global.json / etc. I'd agree that they are then a little bit more hidden, but I can live with it, and I'm used to it. If you have time, I'd be interested in your reasons for why you moved them to root.

Thanks again, and have a nice Sunday! Happy to hear from you.

**Comment by nojaf** [comment]
Hi Ronald,

> This seems to be gone now

Yes, I move `src/docs` to `docs` as this is the default input folder for `fsdocs-tool`.
I didn't see any compelling reason not to have `docs` in that location. While moving it, I didn't take the `.gitignore` file into account.

> Putting the FsHttp.sln, Directory.Build.props and also global.json in the repo's root isn't what I usually do.

Yes, I found this to be atypical and frustrating when opening the solution in Rider.
While in VSCode you typically open the repository as a folder, in Rider you will open the solution file instead.

The source of frustration is that you cannot see any files in the repository above the `src` folder:
image

The advantage of opening a solution in the root:
image

All files are available.

Having solutions, Directory.Build.props and global.json in the root of the repository are actually very common. 

Some examples of other projects I contribute to that follow this pattern:
- https://github.com/fsprojects/fsharp.formatting
- https://github.com/fsprojects/fantomas
- https://github.com/dotnet/fsharp
- https://github.com/fsharp/fsautoComplete/
- https://github.com/fsprojects/FSharpLint
- https://github.com/fable-compiler/fable
- https://github.com/slaveOftime/Fun.Build
- https://github.com/ionide/KeepAChangelog
- https://github.com/ionide/ionide-vscode-fsharp

I could go on, but this really is very common, so it felt weird that `fshttp` doesn't follow this convention.

**Comment by RonaldSchlenker** [comment]
I respect your feelings of weirdness, although I don't share them :) It's okay for me doing it the way other would most likely do it, since I see a value in it per se. I definitely remember that weired Rider behaviour, which is the one thing that keeps me from using it! Link: https://twitter.com/SchlenkR/status/1702279268359626800

And again: Thank you very much for your time. I would appreciate future contributions and collaborations a lot - in this repo, or another...

**Comment by RonaldSchlenker** [comment]
Just for the record - in the case anyone might stumble upon this: Another advantage of having the (a single) solution in the root is to be able to run CLI commands directly without changing dir.

**Pull request merged**
