### PR TITLE
Don't add empty cookies to headers

### PR DESCRIPTION
**Pull request by Samuel-Dufour**
Solution tested successfully by updating versions to net7.0.

### CODE REVIEW

**Comment by Samuel-Dufour** [comment]
#109

**Comment by RonaldSchlenker** [comment]
That’s a great improvement, @Samuel-Dufour ! Thank you very much for the contribution. You saved me a lot of work digging into this. 

I’ll merge it soon, alongside other additions and fixes, with a release hopefully this month. 

Again, thanks for your work, and have a nice day.

**Comment by Samuel-Dufour** [comment]
> That’s a great improvement, @Samuel-Dufour ! Thank you very much for the contribution. You saved me a lot of work digging into this.
> 
> I’ll merge it soon, alongside other additions and fixes, with a release hopefully this month.
> 
> Again, thanks for your work, and have a nice day.

My pleasure ! Happy to contribute to your great work !

**Comment by RonaldSchlenker** [comment]
Thanks again! I'll release 10.0.0-preview1 in some minutes...

**Comment by belcher-rok** [comment]
@RonaldSchlenker, I can confirm that 10.0.0-preview2 solved this issue for me. Thank you for the fast turnaround.

**Pull request merged**
